### ISSUE TITLE
Retinaディスプレイ搭載Macでの実行時にmes命令が正しく実行されない

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#1]
RetinaディスプレイMacBookProで動作時に、mes命令で描画された文字列が大きくぼやけて表示されます。
また、同じく実行時の描画文字列の下部と右部が途切れてしまっています。

動作マシンはMacBookPro Retina 2013mid です

**Comment by dolphilia** [comment]
報告ありがとうございます。

すぐに検証してみたい・・・のですが、
非Retinaマシンで開発しているので、自力では解決できそうにないです。

----

何も対応できないというのも心苦しいので、
とりあえずv0.7.6で以下の関数を追加しました。

- isretina()
    - パラメーターなし
    - 非retinaなら0を返す。retinaなら1を返す（はず）。
- getretina()
    - パラメーターなし
    - 倍率を返す（はず）。非retinaの場合は1.0を返す。

----

求む：
以下のコードをRetina環境で実行したスクリーンショット

```
title ""+isretina()+":"+getretina()
line 0,0,300,300
mes "Hello World"
```

**Comment by akatsuki** [comment]
内部エラーが発生しました
配列の要素書式が間違っています

というダイアログが表示されてしまいます。
システム変数の呼び出しに失敗しているように感じます。
<img width="504" alt="error" src="https://cloud.githubusercontent.com/assets/1490632/16949223/79d5f41e-4df4-11e6-84c0-e17aa9e9d25a.png">

**Comment by akatsuki** [comment]
一応現在起きている状態をスクリーンショットに残しました
以下の試験プログラムの実行結果の画像です

```
title "動作テスト"
screen 0,640,360 ;ウインドウ初期化テスト

;各種文字列描画テスト
mes "It looks like very strange." ; アルファベット描画テスト
mes "文字がバグっているようだ" ; 日本語描画テスト
mes "我要那个手机" ; 中国語描画テスト
mes "وأعتقد أنه يبدو مثل الخطوط غريبة." ; その他UTF-8文字テスト

; フォント変更時の描画テスト
font "times",50 ;
pos 0,250 ;
mes "フォント指定は可能もやはり途切れる"

; 以下各種描画テスト
line 0,70,100,70 
boxf 0,100,100,200 ;
stop
```

<img width="777" alt="default" src="https://cloud.githubusercontent.com/assets/1490632/16949563/685d3bc8-4df6-11e6-8cd5-f0ef3b2cac84.png">
![default](https://cloud.githubusercontent.com/assets/1490632/16949567/6c243dc4-4df6-11e6-9e22-467efa0b7f28.png)

また、リッチテキストのクリップボードの貼り付けが、その要素を保ったまま貼り付けることができてしまうようです。
リッチテキストを標準化しないと実行時に貼り付けた文字列が認識されないようなので、加えてご報告させていただきます。
こちらは別途Issueに載せて整理させていただきます。

**Comment by dolphilia** [comment]
動作報告ありがとうございます。
スクリーンショットもありがとうございます。重要なところを確認することができました。

----

line命令のぼやけ：
![2016-07-20 14 51 44](https://cloud.githubusercontent.com/assets/13228693/16976389/8128e376-4e89-11e6-927c-9c9a6dff9ed3.png)

スクリーンショットにある線はスムージングがかかっているので、非Retinaの小さな画素データを拡大していることが分かります。文字がぼやけるのも同じ理由だと思われます。

----

文字が大きい：
![2016-07-20 14 56 22](https://cloud.githubusercontent.com/assets/13228693/16976490/2a0f63fc-4e8a-11e6-8cd4-f26a83db7b43.png)

文字列描画はRetinaに対応しているため、文字が大きくなるようです。（画素データ自体はRetinaに非対応）。文字列は小さな画素データに転写しているため、Retina倍率分、大きい文字が描画されてしまうようです。

----

文字が途切れる：
・・・これは分かりません。正常にRetina環境の文字サイズを取得できていないのか、おそらくはMac版HSP側のバグだと思われます。

----

どうやって修正するか（自分用のメモ）：
- ぼやけ
    - 画素が小さいのが原因なので、Retina倍率を取得して、倍率分大きな画素データを用意する。そうするとHSPプログラマは常にRetinaと非Retinaの両方のことを考慮しないといけなくなるのが憂慮。
- 文字が大きい
    - 小さな画素に対しては、内部的に文字を小さくして描画する
    - 大きな画素に対しては、現状のサイズで描画する
- 文字が途切れる
    - 文字サイズの取得コードを再検討

**Comment by dolphilia** [comment]
文字が途切れる不具合の改善を図ってみました。

----

求む：
以下のバージョンのMac版HSPでのmes命令の動作確認
[hsp-macosx-077.zip](http://hsp.dolphilia.com/release/hsp-macosx-077.zip)

**Comment by dolphilia** [comment]
さらに改善を図ってみました。（文字が途切れる不具合の微調整と、文字サイズへの対応です）。

----

求む：
Retina環境での以下のバージョンのmes命令の動作確認
[hsp-macosx-078.zip](/release/hsp-macosx-078.zip)

**Comment by akatsuki** [comment]
079での動作を確認したところ文字が表示されなくなってしまいました。

以下のテストプログラムの動作結果
```
title "動作テスト"
screen 0,640,360 ;ウインドウ初期化テスト

;カラー確認
color 0,0,0

;各種文字列描画テスト
mes "It looks like very strange." ; アルファベット描画テスト
mes "文字がバグっているようだ" ; 日本語描画テスト
mes "我要那个手机" ; 中国語描画テスト
mes "وأعتقد أنه يبدو مثل الخطوط غريبة." ; その他UTF-8文字テスト

; フォント変更時の描画テスト
font "times",50 ;
pos 0,250 ;
mes "フォント指定は可能もやはり途切れる"

; 以下各種描画テスト
line 0,70,100,70 
boxf 0,100,100,200 ;
stop
```
![default](https://cloud.githubusercontent.com/assets/1490632/17079460/01555ff6-514c-11e6-8cd9-4167638460a6.png)

**Comment by akatsuki** [comment]
077での動作を確認したところ文字の見切れは修正されていましたが、文字サイズは壊れたままでした。
```
title "動作テスト"
screen 0,640,360 ;ウインドウ初期化テスト

;カラー確認
color 0,0,0

;各種文字列描画テスト
mes "It looks like very strange." ; アルファベット描画テスト
mes "文字がバグっているようだ" ; 日本語描画テスト
mes "我要那个手机" ; 中国語描画テスト
mes "وأعتقد أنه يبدو مثل الخطوط غريبة." ; その他UTF-8文字テスト

; フォント変更時の描画テスト
font "times",50 ;
pos 0,250 ;
mes "フォント指定は可能もやはり途切れる"

; 以下各種描画テスト
line 0,70,100,70 
boxf 0,100,100,200 ;
stop
```
![077](https://cloud.githubusercontent.com/assets/1490632/17079491/b8919b94-514c-11e6-8eba-19dc9f71f085.png)

**Comment by dolphilia** [comment]
動作確認ありがとうございます。
とても助かっています。

----

再び改善を図ってみました。
[hsp-macosx-080.zip](http://hsp.dolphilia.com/release/hsp-macosx-080.zip)

**Comment by akatsuki** [comment]
文字の見切れ、サイズ以上ともに修正されています。
ありがとうございます。
![default](https://cloud.githubusercontent.com/assets/1490632/17081713/05bcc88e-519e-11e6-933d-5582b2f220cf.png)
