### ISSUE TITLE
書き出したappがGatekeeperに弾かれてしまう

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#10]
macOS Sierraのアップデートにおいて未署名のappが起動不能にされてしまったため
HSPで書き出したアプリケーションが起動不可能となってしまいました
以下のURLに仕様書がありますが、コマンドラインからも署名が可能なようです
環境設定などを設けて、Developer ID 証明書の入力欄を設けるのはいかがでしょうか
[Code Signning Guide - Apple](https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html)

また、Oracleのサイトにapp署名に関する日本語の記述がありましたので合わせてご覧ください
[Mac での配布用の Java アプリケーションのパッケージ化 - Oracle](http://docs.oracle.com/javase/jp/7/technotes/guides/jweb/packagingAppsForMac.html#sign)

または起動時にGatekeeperをオフにすることを奨励するメッセージを表示することをお勧めします。
これが一番容易だとは思いますが、一方で危険ではあるとも思います。
spctl --master-disableを実行するだけですので、app側からコマンドを呼び出すことも可能かと思います。

**Comment by dolphilia** [comment]
有用な情報に感謝します。

xcode8.0から署名まわりの機能が新しくなっていたので、
アプリの署名を更新してみました。
[hsp-macosx-102b.zip](http://hsp.dolphilia.com/release/hsp-macosx-102b.zip)

Gatekeeperをオンにした状態で、
実行できるか試していただけるでしょうか。

**Comment by akatsuki** [comment]
102bでテスト動作をさせましたがやはり起動できませんでした。
hsed、hsp共に起動時に開発元が未確認であると表示されており、引き続きこれが原因で動作不良を起こしていることが見受けられます

**Comment by dolphilia** [comment]
確認ありがとうございます。とても助かっています。

正規の方法でアプリケーションを検証してみたところ、
hsp.appはアイコンがないとのことでエラーが出ることがわかりました。

不具合を修正した上で、改めてまとめてみました。
[hsp-macosx-102c.zip](http://hsp.dolphilia.com/release/hsp-macosx-102c.zip)
こちらも試していただけるでしょうか。

**Comment by akatsuki** [comment]
開発元の確認はできたようで、無事動作しました。
しかし未だにhsp.appの呼び出しに失敗します。
コンソールを確認しましたがこれといったエラーは見つかりませんでした。

**Comment by dolphilia** [comment]
動作確認ありがとうございます。エラーチェックにも感謝します。

hsp.appが起動できるようになったようなので、
改めて086以前の方法で起動できる可能性が出てきました。

起動方法を変更したバージョンを用意しましたので、（多重起動はできなくなっていますが）
こちらも動作確認をお願いできるでしょうか。

[hsp-macosx-102d.zip](http://hsp.dolphilia.com/release/hsp-macosx-102d.zip)

**Comment by akatsuki** [comment]
やはり呼び出しには失敗しているようです。

**Comment by dolphilia** [comment]
確認ありがとうございます。

調べてみると、外部アプリケーションの呼び出しは、
サンドボックス導入に伴って以来、かなり厳しくなっているようですね。

別な起動方法を見つけたので、実装してみました。
こちらも動作確認をしていただけでしょうか。

[hsp-macosx-102e.zip](http://hsp.dolphilia.com/release/hsp-macosx-102e.zip)

**Comment by akatsuki** [comment]
呼び出しできませんでした

**Comment by dolphilia** [comment]
確認ありがとうございました。
外部アプリの呼び出しは、現状では難しいようですね。

そこで、akatsukiさんの提案を採用して、
初回起動時にGatekeeperをオフにする方法を提示するように変更しました。

同様の内容を記したPDF「macOS Sierraをお使いの皆さまへ」も同封して、
[hsp-macosx-103.zip](http://hsp.dolphilia.com/release/hsp-macosx-103.zip)
としました。

**Comment by akatsuki** [comment]
最新版を拝見しました、文言に修正があります。
spctlコマンドは管理者権限が必要なのでsudoをつけないと解除できません
`sudo spctl --master-disable`

それと、「システム環境設定＞セキュリティとプライバシー＞全てのアプリケーションを許可二チェックを入れてください」といった文章を入れないと、ゲートキーパーを解除するだけに終わります

**Comment by akatsuki** [comment]
それと一応確認ですが、appの書き出し自体はできています
hsp.appを手動起動すれば結果の表示はできています。
hsed.appからhsp.appを起動することができないということです
この内容で伝わっていますでしょうか

**Comment by dolphilia** [comment]
ご指摘ありがとうございます。

該当の箇所を修正しました。
[hsp-macosx-103.zip](http://hsp.dolphilia.com/release/hsp-macosx-103.zip)

はい、伝わっています。

少し開発寄りの話題になりますが、
アプリから別アプリケーションを起動する方法は、
３つあると認識しています。

- NSTask を使用する方法（UNIXのopenコマンドを使う）
- NSWorkspace launchApplication を使用する方法
- AppleScript を使用する方法

私に実装した経験があったのが上２つであったという理由で、すぐに試す流れになりました。
しかし、その２つでは起動できないことを確認していただきました。

３つ目の方法なら、もしかしたらという可能性は残っています。
やり方がわからず手間取ってしまいましたが、実装できました。
こちらも試していただけると助かります。
[hsp-macosx-103b.zip](http://hsp.dolphilia.com/release/hsp-macosx-103b.zip)

これでもダメなら・・・、
今の私には解決方法が見つからないです。

**Comment by akatsuki** [comment]
やはり動作しませんでした
「NSTask を使用する方法（UNIXのopenコマンドを使う）」これが動かないのは不思議ですね・・・。
サンドボックス街にアクセスする方法はないのでしょうかね・・。

**Comment by akatsuki** [comment]
ちょっとずれますが、そもそもアプリケーション内でテスト動作を行うことは不可能ですか？
外部にappをかき出すのではなく、同一app内でインタプリタを行い表示するという実装です。
もし可能であれば、テスト動作はサンドボックス内、書き出したアプリケーションは従来通りhsp.app
という具合に分別できそうですが

**Comment by akatsuki** [comment]
試してみてほしい案としては、
hsed.appの中にhsp.appを格納して、書き出しの時にそれを外に出す（app内だからsandboxに引っかからずに起動できるかも？）
hsp.appをhsed.appと同一のフォルダではなく、「ライブラリ/Application Support/hsp/」に格納する（アプリケーションサポートフォルダ内は基本そのアプリケーションのアクセス権で触れるから大丈夫なのではという）

そしてもう一つ考えとしては、そもそもhsp.appのアクセス権がhsed.appにないのではという疑問
仮にsierraのアプデで、かくappのアクセス権が落とされていたとしたらアプリを起動できないのは当たり前で、それも踏まえて管理権限からhsed.appを起動するテストを行ってみる（←メモ）

**Comment by dolphilia** [comment]
__直前のコメントに対して：__

hsed.app内にhsp.appを格納したものを起動してみる、を実装してみました。
３つの起動方法すべてを試せるようにしてあります。
[hsp-macosx-103c.zip](http://hsp.dolphilia.com/release/hsp-macosx-103c.zip)

----

__１つ前のコメントに対して：__

私も似たようなことを考えていました。

実装には幾つか課題があって・・・

- hsp内部のデータをいかに解放するか
  - 外部hsp.appなら終了時に自動解放されるが、インタプリタ方式にすると手動でhsp内部の変数などを解放する必要が出てくる
- エディタとテスト部の実行フェーズをどう管理するか
  - 一旦start.axを生成していたのを、生成せずに直接データを渡すようにするか。実行はマルチスレッドで行うか、そうしないか
- インターフェースをどうするか
  - エディターのUI設計を見直す必要がある

など時間がかかりそうです。

すぐに実現させるのは困難ですが、
将来的には（昨今のAppleの動向からしても）、
この方向で進めていくべきだろう、と考えています。

----

__２つ前のコメントに対して__

実際にはhsed.appもhsp.appもサンドボックス化はしていないのですが、macOS Sierraではセキュリティが強化されたのか、サンドボックスしていないアプリに対しても何らかの制限があるようですね。

でも書類ディレクトリには普通に読み書きできているようなので、（サンドボックス化では制限があるはず）
制限の範囲や強さがわからず、不思議です。

**Comment by akatsuki** [comment]
103cにおいて、全ての実行において動作が確認されました。
また、今回の問題についてはサンドボックスとは別に下記の新機能が問題を起こしているものと思います。
内部格納によって正常に動作したのもこのためかと思います

macOS Sierraで新たに導入されたセキュリティ機能「Gatekeepr Path Randomization」
http://applech2.com/archives/macos-10-12-sierra-gatekeepr-path-randomization.html

**Comment by dolphilia** [comment]
確認ありがとうございました。有用な情報にも感謝します。
[hsp-macosx-104.zip](http://hsp.dolphilia.com/release/hsp-macosx-104.zip)
