### ISSUE TITLE
pset命令で描画されるドットがRetinaにおいて最適化されない

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#11]
psetを使ったドット描画がretinaの1ドットとなっており、非常に小さいです。
mesなど他の命令と同じように、2ドット四方4ドット分で描画できるように修正をお願いいたします

**Comment by dolphilia** [comment]
報告ありがとうございます。

screen命令でウィンドウサイズが変更されない不具合があったので改善しました。
[hsp-macosx-105.zip](http://hsp.dolphilia.com/release/hsp-macosx-105.zip)

この変更がpsetへの影響がないとも言い切れないので、
このバージョンでも試していただけると助かります。

また、不具合の様子を知りたいので、
次のコードを試していただけるでしょうか。

```
screen 0,320,240
pset 10,10
title ""+getretina()+":"+isretina()
```

私の環境では次のように表示されます。

![testhsp](https://cloud.githubusercontent.com/assets/13228693/19229695/71cb4b00-8f0a-11e6-9d37-429ae445decb.png)

**Comment by akatsuki** [comment]
画面比2:1を確認しました
![ok](https://cloud.githubusercontent.com/assets/1490632/19251995/3f8af3fc-8f7d-11e6-9cf3-d18e130482bc.png)
正常に動作しました、ありがとうございます
