### ISSUE TITLE
title命令のp1に指定した文字列後のダブルクオーテーションがウインドウに映り込む

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#2]
title命令を実行した際、ダブルクオーテーションがウインドウタイトル部に映り込むことがあります。
再現性があまり高く無いのですが。
概ね特定の２バイト文字をタイトルの最後として入力した際にダブルクオーテーションが写り込みます。

```
title "雑"
stop
```

```
title "後"
stop
```

他にも"ト"や"嶋"、"蜜"などがあります。
漢字であることが多いように感じますが、カタカナなどの例もあるので一概に言えない感じです。

**Comment by dolphilia** [comment]
報告ありがとうございます。

OpenHSPとの文字コードの違いで生じる不具合のようです。mes命令など、文字列を扱う他の命令でも同様の現象がみられるようです。（noteloadでテキストから文字列読み込む場合は大丈夫だと思います）。

----

原因：
これは予想ですが、Mac版HSPはUTF-8を使用しているので、３バイト文字などが使用されると、OpenHSP内部ではShift-JISで２バイトx2として解釈されてダブルクオーテーションまで映り込む、というようなことが起こっているのかもしれません。

----

対応状況：
- Shift-JISに関係する部分（全角チェック）を、しらみ潰しにUTF-8化してみましたが、部分的に改善はできたのですが、別の問題が出てくるので、これは失敗でした。
- コードをShift-JIS化して実行しようとも試みましたが、これも失敗しました。

意外にやっかいな不具合なので、
解決の良い案を思いつくまでは、一旦保留にしたいと思います。

----

暫定的な対策は、文字列の末尾に半角空白を入れる、という感じでしょうか。

```
title "雑 "
stop
```

**Comment by dolphilia** [comment]
解決しました。

OpenHSPの[チェンジセット 805](http://dev.onionsoft.net/trac/openhsp/changeset/805)を適用したところ、UTF-8ソーススクリプトの読み込みが可能になり、それに伴う形でこの不具合が解消されました。

適用したバージョン：[hsp-macosx-079.zip](/release/hsp-macosx-079.zip)

----

以下、動作確認です。

```
title "雑"
stop
```

![test](https://cloud.githubusercontent.com/assets/13228693/17054547/bf7a87fa-5042-11e6-98c1-9a842b1315aa.png)

**Comment by akatsuki** [comment]
ありがとうございます動作を確認いたしました。
修正お疲れ様です。
