### ISSUE TITLE
repeatやgotoが正常に動作しない

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#3]
repeat - loopやgotoなどの繰り返し動作やとばし動作が行われません。
以下のコマンドをテストしましたが文字列は移動せず、表示にもwaitで指定した以上の時間がかかってしまいました。（waitとawaitに関しては整理のため別件でissue登録します）

```
title "test"
mes "テスト１"
wait 100
x = 0

repeat 100
    redraw 0
    cls 1 ; 実行がわかりやすいよう画面背景色変更
    x = x + 2
    pos x,20
    mes "動くはず"
    redraw 1
    await 100
loop
stop
```

何がトリガーになっているのかが全くわからないのですが、
こういった場合にhsp.appに過去に実行した命令結果が残ってしまい、
新しい命令が受け付けられないこともあります。

**Comment by dolphilia** [comment]
報告ありがとうございます。

cls命令に不具合があったので、修正しました。

[hsp-macosx-081.zip](http://hsp.dolphilia.com/release/hsp-macosx-081.zip)

**Comment by akatsuki** [comment]
正常な動作を確認しました
