### ISSUE TITLE
repeatやgotoで構成されたループのあるプログラムでwaitとawaitが正常に動作しないことがある

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#4]
以下のようなloopを含むプログラムでwait,awaitが正常に動作しません。

```
y=100
x=100
*loop
wait 100
x=x+10
pos x,y
mes "1秒だよ"
goto *loop
```

以下のようにloopを含まなければ正常に動作します

```
wait 100 ;waitテスト
mes "1秒だよ"
wait 100
mes "1秒だよ"
wait 100
mes "1秒だよ"
wait 100
mes "1秒だよ"
await 1000 ;awaitテスト
mes "1秒だよ"
await 1000
mes "1秒だよ"
await 1000
mes "1秒だよ"
await 1000
mes "1秒だよ"
stop
```

こちらの実験時にもhsp.appに過去に実行した命令結果が残ってしまい正常に動作しませんでした。

**Comment by dolphilia** [comment]
報告ありがとうございます。

----

本家HSPで実行してみたところ、`error 7：ラベル名はすでに使われています`と出たので、
`*loop`が予約語`loop`と被っているのが原因と思われます。

予約語を回避すれば正常に動作すると思います。

```
y=100
x=100
*_loop
wait 100
x=x+10
pos x,y
mes "1秒だよ"
goto *_loop
```

----

対策：
コンパイルエラーが目立たないのは不親切な仕様だったので、
エラーダイアログを表示するように変更しました。

![default](https://cloud.githubusercontent.com/assets/13228693/17082196/f5f39484-51af-11e6-9ba9-0537cc41b4f9.png)

またコンパイルエラーが生じたときは、
hsp.appを実行しないように変更しました。

[hsp-macosx-082.zip](http://hsp.dolphilia.com/release/hsp-macosx-082.zip)

**Comment by akatsuki** [comment]
動作を確認しました、waitは正常に動いています。
ありがとうございました。
