### ISSUE TITLE
高解像度ディスプレイ時に画像をぼかさない設定の導入

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#5]
高解像度ディスプレイを利用時に通常ではmacOSの機能でぼかしを入れたアップコンバートが入りますが、
これではドット絵を主体とした2DRPGのようなゲームを作る上であまり好ましくありません。

そこでコンバート時にRetinaでの起動にぼかしを入れるかを選択するチェックマークを
hsed.appの詳細設定に入れてもらえませんか？
hsp.appの動作としてはシステムから利用中のMacがretinaかを判別して
現在ドットバイドットなのをドットバイ４ドットにしてOS側に高解像度ディスプレイ対応appとして振る舞う
というのを考えていますがいかがでしょうか。
もしくはぼかしを入れるかどうかを選択するapp設定がOS側にあるのかもしれません。

Retinaに対応できれば一番ですが、それは一番難しそうですし。。

HSP自体のプログラミングとは関係がない部分ですので
非常に面倒な作業になってしまうと思います。
もしよければ検討して欲しいといった程度の要望なので、気が向いた時によろしくお願いいたします。。

**Comment by dolphilia** [comment]
ナイスなIssues、ありがとうございます。
ドット絵がぼけてしまうのは好ましくない、というのは同感です。

解決案としては、前者が良いと思います。
Retinaだった場合は、現在の低解像度なピクセルデータをズームする（ぼかさない計算法で）。

絵がボケないのはHSPユーザーが自然に求めることだと思うので、
むしろ初期設定でそのように動作する、という方向性でも良いかと思っています。

----

試作品です。動作確認していただけると助かります。

[hsp-macosx-085.zip](http://hsp.dolphilia.com/release/hsp-macosx-085.zip)

テスト用のドット絵：

![maptip](https://cloud.githubusercontent.com/assets/13228693/17237874/6c4a7b9a-5591-11e6-9108-6dfc7c78894f.png)

**Comment by akatsuki** [comment]
picloadがうまく動かなかったので
mesで動作を確認しました。
アンチエイリアシングがかかっちゃってたけれどちゃんとジャギってます！
