### ISSUE TITLE
フォントに標準でアンチエイリアシングがかかっている

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#6]
ビルド085を利用してジャギーなフォントを見ようとした際に、面白い発見がありました。

Macのフォントレンダリングを使っているからなのか
Win版HSPとは違い、標準で文字に綺麗なアンチエイリアシングがかかっています。
非常に綺麗だし「さすがMacだなぁ」とは感じましたが・・・

これは逆に言うとfont命令の第三パラメータのフォントスタイル16、
「アンチエイリアシング」を設定もしていないのに利用しているということにもなります。
Winとの互換性を考慮に入れると、この差異はあまり好ましくありません。
もし可能であれば、標準のレンダリング設定をアンチエイリイアシング無しに設定できますか？

![default](https://cloud.githubusercontent.com/assets/1490632/17242379/cd51c950-55b1-11e6-8def-3638fefd50f1.png)
[息抜きに読み上げてみた](https://vine.co/v/5KPBUVUAFuT)

**Comment by dolphilia** [comment]
報告ありがとうございます。

標準でアンチエイリアシングを無効にして、
font命令で任意にアンチエイリアシングできるようにしました。

[hsp-macosx-086.zip](http://hsp.dolphilia.com/release/hsp-macosx-086.zip)

----

私の環境では正常に動作していますが、
Retinaでの動作は分からないので、確認してくださると助かります。

![159](https://cloud.githubusercontent.com/assets/13228693/17274941/1de0e604-5732-11e6-91b7-99606102ce56.png)

----

issue男とは呼んでないので、どうぞ安心してください。

なお、issue立ては一度に１つか２つにしてくださると、
ゆったり取り組めるので、たいへん助かります。

**Comment by akatsuki** [comment]
build 086を利用しています。
アンチエイリアシングなしの場合のフォントサイズが限りなく小さくなっており、
また下に飛び出している特定のアルファベット"q"や"j"などの下の部分が途切れたり
横に伸びている事がわかりました。
font命令でサイズ矯正はできます。
font 命令でアンチエイリアシングをかけたところサイズが元に戻りました。
```
mes "test q"
font "",,16
mes "test q"
font "",100
mes "test q"
stop
```
![test](https://cloud.githubusercontent.com/assets/1490632/17289182/7868fb02-5813-11e6-89b1-ed2c7bc606f4.png)

**Comment by dolphilia** [comment]
確認ありがとうございます。
修正を試みてみました。

[hsp-macosx-088.zip](http://hsp.dolphilia.com/release/hsp-macosx-088.zip)

----

Issuesの #7 に関係することでもあるのですが、
下のコードを確認していただけないでしょうか。

```
color 255,0,0
line 0,0,100,100
color 0,0,0
mes "HelloWorld"
```

文字とラインの重なりの箇所が、
正常に描画されているか、確認したいと思っています。

![screenshot](https://cloud.githubusercontent.com/assets/13228693/17315380/f4026496-58a5-11e6-9bab-654b4f653cb8.png)

**Comment by akatsuki** [comment]
重なりを拡大してみました。
文字の方が上ですね
かつ、文字とかかっている部分の線にアンチエイリアシングがかかっています
![hello world](https://cloud.githubusercontent.com/assets/1490632/17316450/e20097a0-58ae-11e6-995e-0ff8b9d43d5f.png)

**Comment by dolphilia** [comment]
確認ありがとうございます。

背景がぼやけないよう、修正を試みました。

[hsp-macosx-089.zip](http://hsp.dolphilia.com/release/hsp-macosx-089.zip)

**Comment by akatsuki** [comment]
ぼやけていないのを確認しました
バグ除去お疲れ様です
