### ISSUE TITLE
picloadとcelloadができない

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#7]
picload命令とcellload命令が動作しません。
とはいえ何かしらのエラーが出るのではなく、ただ画像が表示されないといった具合です。
テストに使用した画像はjpgファイルでタイトルは"pic.jpg"と全てアルファベットのものを使いました。
画像ファイルの指定を絶対位置で指定なのではと考え、和式Windows式（ディレクトリを¥で）とUnix式（ディレクトリは/で）を試しましたが、どちらも動作しませんでした。バックスラッシュはまだ試していません。
この場合だと内部エラーの警告ウインドウが出ます。

**Comment by dolphilia** [comment]
報告ありがとうございます。とても助かっています。

エラーが出ずに画像が表示されないとのことで、
正直なところ、原因の検討がつきません。

----

以下のバージョンでpicloadを試していただけるでしょうか。

[hsp-macosx-086b.zip](http://hsp.dolphilia.com/release/hsp-macosx-086b.zip)

次のようなダイアログが表示されるはずです。

![picload](https://cloud.githubusercontent.com/assets/13228693/17275249/197ba7f2-573c-11e6-8cec-98375c6f5467.png)

少しでも足がかりを得たいので、
ダイアログのスクリーンショットを送ってくださると助かります。

----

ちなみにcel系命令はまだ未対応です。
（現状のcelloadは内部的にはpicloadと同じです）

**Comment by akatsuki** [comment]
試しました。
```
picload "pic.jpg"
stop
```
<img width="532" alt="default" src="https://cloud.githubusercontent.com/assets/1490632/17289366/64c3eee4-5814-11e6-978c-d02e5e9d2531.png">


![pic](https://cloud.githubusercontent.com/assets/1490632/17289385/719920c6-5814-11e6-870f-5c29e9dc5157.jpg)
pic.jpgはこんな画像です

![default](https://cloud.githubusercontent.com/assets/1490632/17289391/7a649b36-5814-11e6-815a-36338b7c38ee.png)
こういった画面が映されます

**Comment by dolphilia** [comment]
修正の難しい不具合だったので、
画像の読み込み方式から書き直しました。

[hsp-macosx-090.zip](http://hsp.dolphilia.com/release/hsp-macosx-090.zip)

動作を確認していただけると助かります。

**Comment by akatsuki** [comment]
上部1/5程度は幅が正しく表示されるようになりましたが、下部の描画にエラーが残っています
![build90](https://cloud.githubusercontent.com/assets/1490632/17322513/bd6aabfe-58d8-11e6-9344-668319a059e2.png)

**Comment by akatsuki** [comment]
追記です。
picload命令の第一パラメータを1や2に指定したところ正常に描写されました。
一方でパラメータを初期値の0にした際に上記のエラーが発生することから、
ウインドウの初期化と画像の描画が同時に行われてしまっているのではないかと考えられます。

**Comment by dolphilia** [comment]
ありがとうございます。
私の環境でも同様の現象を再現することができました。

暫定的ですが、修正を試みてみました。

[hsp-macosx-091.zip](http://hsp.dolphilia.com/release/hsp-macosx-091.zip)

動作確認していただけると助かります。

**Comment by akatsuki** [comment]
正常な動作を確認しました。
バグフィックスお疲れ様です。
