### ISSUE TITLE
hsp.appの複数同時起動

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#8]
現在、hsed.appのウインドウがいくつあっても掻き出されるhsp.appは一つとなっており
他ウインドウがプログラムを実行中に別ウインドウを実行しようとしても
既にあるhsp.appのウインドウがアクティブになるだけなので、必ず一度停止ボタンを押す必要があります
そのため本家HSPのように幾つかのhspウインドウからプログラムをその都度個別に実行することができません

本家HSPの使用があやふやなのですが、F5での仮実行と書き出しは別だった気がします。
そこで、現在は書き出しは仮実行も本実行も同列ですが、本書き出し時とは別に仮実行の場合は
"ユーザー/liberally/application support/HSP"フォルダにhsp.appの仮書き出しを行ってはいかがでしょう？
temp1, temp2といったフォルダを実行時に内部に作りhsp.appを作成、app停止時に削除をすれば複数のプログラムの同時実行が可能かと思います。

**Comment by dolphilia** [comment]
報告ありがとうございます。

同時起動できるようにしました。
[hsp-macosx-087.zip](http://hsp.dolphilia.com/release/hsp-macosx-087.zip)

----

同時起動できるようにした関係で、
アプリケーションの停止が困難になったので、
エディターの停止ボタンは廃止しました。

代わりに、
hsp.appのウィンドウを閉じたときに、
アプリケーションを終了するよう変更しました。

**Comment by akatsuki** [comment]
正常な動作を確認しました。
