### ISSUE TITLE
macOS Sierraで命令が実行されない

### ISSUE THREAD

**Issue by akatsuki** [dolphilia/hsp-macosx#9]
hsed.appは動作しますが、命令を実行しようとしてもhsp.appが起動しません。

**Comment by dolphilia** [comment]
エディタの実行ボタンを押してもhsp.appが起動しない、ということでしょうか？

もしかするとIssues #8 の多重起動の件で、起動方法を変更したのが原因かもしれません。

確かめたいので、もし可能でしたら、
[hsp-macosx-086.zip](http://hsp.dolphilia.com/release/hsp-macosx-086.zip)か、それ以前のバージョンで起動できるか確認していただけないでしょうか。

当方のMacはちょっと古くて、
macOS Sierraのアップデート対象外になっていて動作確認できずにいたので、
ご報告ありがたいです。

**Comment by akatsuki** [comment]
086を起動したところ、エディタは起動しますが、相変わらず実行はできませんでした。
また、086でのテストの際、Dockのアイコンに102では見られなかった利用不可能マークが表示されました。
![default](https://cloud.githubusercontent.com/assets/1490632/18874571/3f27c636-84fd-11e6-94eb-7a52eb92cbd2.png)
動作自体はしているにもかかわらずこのマークが出るのは少し不思議ですね。。。

**Comment by dolphilia** [comment]
確認ありがとうございます。
起動方法が原因というわけではなさそうですね。

今のところ、さっぱり原因がわからないです。
macOS Sierraでhsp.appをビルドできれば、何かつかめるのかもしれませんが・・・

ところで、
hsp.appは単体では（アイコンをダブルクリック）起動するでしょうか。

利用不可能マークの件も気になりますね。
086のころはxcode7.xで、最新のものはxcode8.0でビルドしているので、
それが関係しているのかもしれません。

**Comment by akatsuki** [comment]
原因がわかりましたのでご報告させて頂きます。
SierraよりmacOSのファイアーウォールであるGatekeeperが強化され、署名のないすべてのアプリケーションが起動不可能な状態になっていました。
`spctl --master-disable`
これをターミナルで打ち込みGatekeeperを停止することで今まで通りの正常な動作を取り戻すことができましたが、アプリケーションの動作保障の観点から言うと署名の問題には対応が必要かと思います。
これについてはタイトルややり取りなどが紛らわしいですし、一応新しいissueとして再投稿させていただきますね。

**Comment by dolphilia** [comment]
有用な情報ありがとうございます。
issues #10 に引き継ぎたいと思います。
